[workspace]
resolver = "2"

# Please ensure that each crate comes before any other crate that depends on it
members = ["core", "net", "p2p", "jsonrpc"]

[workspace.package]
description = "An infrastructure for peer-to-peer, decentralized, and collaborative software."
version = "0.1.0"
edition = "2021"
homepage = "https://karyontech.net"
repository = "https://github.com/karyontech/karyon"
license = "GPL-3.0"
authors = ["hozan23 <hozan23@karyontech.net>"]

[workspace.dependencies]
karyon_core = { path = "core", default-features = false }
karyon_net = { path = "net", default-features = false }
karyon_jsonrpc = { path = "jsonrpc", default-features = false }
karyon_p2p = { path = "p2p", default-features = false }
