[package]
name = "karyons_p2p"
version.workspace = true 
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
karyons_core.workspace = true
karyons_net.workspace = true

smol = "1.3.0"
async-trait = "0.1.73"
futures-util = {version = "0.3.5", features=["std"], default-features = false }
log = "0.4.20"
chrono = "0.4.30"
bincode = { version="2.0.0-rc.3", features = ["derive"]}
rand = "0.8.5"
thiserror = "1.0.47"
semver = "1.0.20"
sha2 = "0.10.8"

# tls
async-rustls = { version = "0.4.1", features = ["dangerous_configuration"] }
rcgen = "0.11.3"
yasna = "0.5.2"
x509-parser = "0.15.1"

[[example]]
name = "peer"
path = "examples/peer.rs"

[[example]]
name = "chat"
path = "examples/chat.rs"

[[example]]
name = "monitor"
path = "examples/monitor.rs"

[dev-dependencies]
async-std = "1.12.0"
clap = { version = "4.4.6", features = ["derive"] }
ctrlc = "3.4.1"
easy-parallel = "3.3.1"
env_logger = "0.10.0"
