[package]
name = "karyon_core"
description = "Internal crate for Karyon project."
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["smol"]
crypto = ["dep:ed25519-dalek"]
tokio = ["dep:tokio"]
smol = ["dep:smol", "dep:async-process"]

[dependencies]
pin-project-lite = "0.2.13"
log = "0.4.21"
bincode = "2.0.0-rc.3"
chrono = "0.4.35"
rand = "0.8.5"
thiserror = "1.0.58"
dirs = "5.0.1"
async-channel = "2.2.0"

# crypto feature deps
ed25519-dalek = { version = "2.1.1", features = ["rand_core"], optional = true }

# smol feature deps
async-process = { version = "2.1.0", optional = true }
smol = { version = "2.0.0", optional = true }

# tokio feature deps
tokio = { version = "1.37.0", features = ["full"], optional = true }
once_cell = "1.19.0"
