[package]
name = "karyon_core"
description = "Internal crate for Karyon library."
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["smol"]
crypto = ["dep:ed25519-dalek"]
tokio = ["dep:tokio"]
smol = ["dep:smol", "dep:async-process"]

[dependencies]
log = "0.4.21"
thiserror = "1.0.61"
chrono = "0.4.38"
rand = "0.8.5"
dirs = "5.0.1"
parking_lot = "0.12.3"
once_cell = "1.19.0"

# async 
async-channel = "2.3.1"
pin-project-lite = "0.2.14"
async-process = { version = "2.2.3", optional = true }
smol = { version = "2.0.0", optional = true }
tokio = { version = "1.38.0", features = ["full"], optional = true }

# encode
bincode = "2.0.0-rc.3"

# crypto
ed25519-dalek = { version = "2.1.1", features = ["rand_core"], optional = true }
