[package]
name = "karyons_core"
version.workspace = true 
edition.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.3.0"
pin-project-lite = "0.2.13"
log = "0.4.20"
bincode = { version="2.0.0-rc.3", features = ["derive"]}
chrono = "0.4.30"
rand = "0.8.5"
thiserror = "1.0.47"
dirs = "5.0.1"
