[package]
name = "karyon_core"
version.workspace = true 
edition.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "2.0.0"
pin-project-lite = "0.2.13"
log = "0.4.21"
bincode = "2.0.0-rc.3"
chrono = "0.4.35"
rand = "0.8.5"
thiserror = "1.0.58"
dirs = "5.0.1"
async-task = "4.7.0"
async-lock = "3.3.0"
async-process = "2.1.0"

ed25519-dalek = { version = "2.1.1", features = ["rand_core"], optional = true}


[features]
default = []
crypto = ["dep:ed25519-dalek"]


