[package]
name = "karyon_jsonrpc"
description = "A fast and lightweight async JSONRPC2.0 implementation."
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme="README.md"


[features]
default = ["smol"]
ws = ["karyon_net/ws", "async-tungstenite"]
unix = ["karyon_net/unix"]
smol = [
  "karyon_core/smol",
  "karyon_net/smol",
  "karyon_jsonrpc_macro/smol",
  "futures-rustls",
  "async-tungstenite?/async-std-runtime",
]
tokio = [
  "karyon_core/tokio",
  "karyon_net/tokio",
  "karyon_jsonrpc_macro/tokio",
  "tokio-rustls",
  "async-tungstenite?/tokio-runtime",
]

[dependencies]
karyon_core = { version = "0.1.1", path = "../core", default-features = false }
karyon_net = { version = "0.1.1", path = "../net", default-features = false, features = [
  "tcp",
  "tls",
] }

karyon_jsonrpc_macro = { version = "0.1.1", path = "jsonrpc_macro", default-features = false }

log = "0.4.21"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
async-trait = "0.1.77"
async-channel = "2.3.1"

async-tungstenite = { version = "0.25.0", default-features = false, optional = true }

futures-rustls = { version = "0.25.1", optional = true }
tokio-rustls = { version = "0.26.0", optional = true }

[dev-dependencies]
env_logger = "0.11.3"
rcgen = "0.13.1"
rustls-pemfile = "2.1.2"
smol = "2.0.0"
webpki-roots = "0.26.1"
