[package]
name = "karyon_jsonrpc"
version.workspace = true
edition.workspace = true

[features]
default = ["smol"]
smol = [
  "karyon_core/smol",
  "karyon_net/smol",
  "karyon_jsonrpc_internal/smol",
  "karyon_jsonrpc_macro/smol",
  "dep:futures-rustls",
  "async-tungstenite/async-std-runtime",
]
tokio = [
  "karyon_core/tokio",
  "karyon_net/tokio",
  "karyon_jsonrpc_internal/tokio",
  "karyon_jsonrpc_macro/tokio",
  "async-tungstenite/tokio-runtime",
  "dep:tokio-rustls",
]

[dependencies]
karyon_core = { workspace = true, default-features = false }
karyon_net = { workspace = true, default-features = false }

karyon_jsonrpc_macro = { path = "jsonrpc_macro", default-features = false }
karyon_jsonrpc_internal = { path = "jsonrpc_internal", default-features = false }

log = "0.4.21"
rand = "0.8.5"
async-tungstenite = { version = "0.25.0", default-features = false }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
memchr = "2.7.1"
async-trait = "0.1.77"

futures-rustls = { version = "0.25.1", optional = true }
tokio-rustls = { version = "0.26.0", optional = true }

[dev-dependencies]
env_logger = "0.11.3"
rcgen = "0.13.1"
rustls-pemfile = "2.1.2"
smol = "2.0.0"
webpki-roots = "0.26.1"
