[package]
name = "karyon_jsonrpc"
version.workspace = true 
edition.workspace = true

[dependencies]
karyon_core.workspace = true
karyon_net.workspace = true

smol = "2.0.0"
log = "0.4.21"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
memchr = "2.7.1"

[[example]]
name = "server"
path = "examples/server.rs"

[[example]]
name = "client"
path = "examples/client.rs"

[dev-dependencies]
env_logger = "0.11.3"
