[package]
name = "karyons_jsonrpc"
version.workspace = true 
edition.workspace = true

[dependencies]
karyons_core.workspace = true
karyons_net.workspace = true

smol = "1.3.0"
log = "0.4.20"
rand = "0.8.5"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
memchr = "2.6.4"

[[example]]
name = "server"
path = "examples/server.rs"

[[example]]
name = "client"
path = "examples/client.rs"

[dev-dependencies]
env_logger = "0.10.0"
