[package]
name = "karyon_net"
version.workspace = true 
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
karyon_core.workspace = true

smol = "1.3.0"
async-trait = "0.1.73"
log = "0.4.20"
bincode = { version="2.0.0-rc.3", features = ["derive"]}
thiserror = "1.0.47"
url = "2.4.1"
futures-rustls = "0.25.1"
