[package]
name = "karyon_net"
version.workspace = true 
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
karyon_core.workspace = true

smol = "2.0.0"
async-trait = "0.1.77"
log = "0.4.21"
bincode = { version="2.0.0-rc.3", features = ["derive"]}
thiserror = "1.0.58"
url = "2.5.0"
futures-rustls = "0.25.1"
async-tungstenite = "0.25.0"
ws_stream_tungstenite = "0.13.0"
